# Generated by Django 4.2.5 on 2023-09-08 12:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finish',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
