# Generated by Django 4.2.5 on 2023-09-08 12:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_alter_tasks_finish_alter_tasks_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finish',
            field=models.DateField(verbose_name={'type': 'date'}),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='start',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
