# Generated by Django 4.2.5 on 2023-09-08 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_tasks_finish_alter_tasks_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='finish',
            field=models.DateField(verbose_name=dict),
        ),
    ]
